### ISSUE TITLE
Localization 

### ISSUE THREAD

**Issue by KovalevArtem** [builtbybel/privatezilla#12]
It is sad that the application is only in English - I propose to translate.
I am ready to help in the translation into Russian.
(For example, you can use Weblate, or any other service. It is completely free for open source projects.)

**Comment by caralu74** [comment]
I agree with Mr @KovalevArtem I could help to translate into Spanish. I propose .po or .xlf files that can be translated with poedit.

**Comment by Wasps0** [comment]
I can do french

**Comment by caralu74** [comment]
Do not forget us! We just need a .po file or an xliff file, so as you keep working with the code we can work with localization.

**Comment by Belim** [comment]
this was never on my agenda but i might put it on my to-do list. currently i am very busy and only take care of my hobby projects during the breaks :shit: :sleeping:

**Comment by caralu74** [comment]
I think I understand. I´ll be waiting. and keep hacking!

**Comment by Belim** [comment]
I've added localization support in latest release :smiley:
https://github.com/builtbybel/privatezilla/releases/tag/0.40.0

**Comment by peter9811** [comment]
@KovalevArtem 
Check this: https://crowdin.com/project/privatezilla-traduccin/ru

**Comment by peter9811** [comment]
@Wasps0 
Check this: https://crowdin.com/project/privatezilla-traduccin/fr

**Comment by Belim** [comment]
Localization support has been added with release 0.40
Instructions how-to translate can be found here https://github.com/builtbybel/privatezilla/wiki/Translate

**Comment by comradekingu** [comment]
@Belim Would have contributed if it wasn't on Crowdin.

**Comment by Belim** [comment]
@comradekingu well, there you have it.
crowdin came later. first there was [this](https://github.com/builtbybel/privatezilla/wiki/Translate) :grin:

**Comment by caralu74** [comment]
I think the same, I´d prefer to edit locally. I use PoEdit

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by comradekingu** [comment]
@Belim I don't so much mind how bad of a solution it was. Crowdin is a non-starter.
