### ISSUE TITLE
Analyze Revert and Apply button not visible on Hi-Dpi displays

### ISSUE THREAD

**Issue by That-Dude** [builtbybel/privatezilla#16]
MacBook Pro 13 with freshly installed Windows 10 v2004 via Bootcamp, the buttons are not visible, I suspect this is due to the default Hi-DPI display settings on modern screens.

Tried maximizing the window and resizing the window to make it small and force a re-draw, but still no buttons.

Workaround: Press TAB a few times and guess where the APPLY button is located, then press ENTER.

Suggestion: Move the buttons to the top of the Window, add keyboard shortcuts such as ALT+A for Apply.

**Comment by Belim** [comment]
Can you please show me screenshot?  i think i should be able to solve this without moving the buttons

**Comment by That-Dude** [comment]
![Capture](https://user-images.githubusercontent.com/6509533/91177247-51a1b580-e6db-11ea-9b11-3e8d8a6bbf37.PNG)
![Capture1](https://user-images.githubusercontent.com/6509533/91177254-549ca600-e6db-11ea-84aa-df15b65412ed.PNG)

**Comment by Belim** [comment]
Fixed here https://github.com/builtbybel/privatezilla/releases/tag/0.30.2
