### ISSUE TITLE
Suggestion: translation tool

### ISSUE THREAD

**Issue by peter9811** [builtbybel/privatezilla#17]
Hi, I want do a suggestion
I love help to translate different apps to my language (Spanish), but I try do it with this app too, but I don't understand a lot the other app...

I'm using this web to help to translate string. Support xml, ini, and others types of files...
https://crowdin.com/

**Comment by peter9811** [comment]
Sorry. I fixed the problem with the app... 

I'm doing the translation, but if you want, check the app that I was recommended

**Comment by peter9811** [comment]
Hmmm... Sorry I don't like use the "tool", it's so complicated to me... 

I did this: https://crowdin.com/project/privatezilla-traduccin

I'm doing manually the translation to Spanish...

**Comment by Belim** [comment]
sry, never had anything to do with such services and I don't know anything about them. 
But I will add some info to the wiki, if they support .xml

Thanks a lot for your help. As a short note, the file `MainWindow.resx` can be ignored because the strings are all in `Resources.resx`

**Comment by peter9811** [comment]
@Belim 
I upload the original files, and Crowdin support too the `.resx` file.

I'm doing the translation. I think that in some hours I going to do the pull with the file...
If anyone want help, can do it on the web and I can export the language file...

-A question: what name will be have the file? `Resources.es.resx`?

**Comment by Belim** [comment]
> A question: what name will be have the file? `Resources.es.resx`?

Excactly :wink:
