### ISSUE TITLE
Ru translation file

### ISSUE THREAD

**Issue by Almanex** [builtbybel/privatezilla#22]
Translation into Russian, [Ru-ru.zip](https://github.com/builtbybel/privatezilla/files/5251407/Ru-ru.zip)

**Comment by Belim** [comment]
Many thanks for this. Will be shipped with todays release 0.40.2

Another translation is running [here](https://crowdin.com/project/privatezilla-traduccin/ru#) I guess this one does not come from you ?

**Comment by Almanex** [comment]
I translated manually, but I will gladly take part in translating the program into crowdin

**Comment by Belim** [comment]
Since i don't use and know this service, you might have to contact the project manager of the translation there (he has commited also [here](https://github.com/builtbybel/privatezilla/pulls?q=is%3Apr+is%3Aclosed)). 

Maybe you can upload your finished translation also on crowdin

**Comment by peter9811** [comment]
@Almanex 
I added your translation file, and apparently all strings are translated. Thanks
