### ISSUE TITLE
Community packages not working

### ISSUE THREAD

**Issue by BeatLink** [builtbybel/privatezilla#26]
Hello, i tried following the instructions to extract the community package to the privatezilla package but it still wont run

**Comment by BeatLink** [comment]
Found it. Turns out i have to rename the extracted folder from "packages" to "scripts".

**Comment by Belim** [comment]
Thank you for pointing that out. I have packed it again as `scripts` directory and will refresh the instructions

**Comment by BeatLink** [comment]
Awesome! I love privatezilla and i cant wait to see this implemented :D

**Comment by DrSaad77** [comment]
> Awesome! I love privatezilla and i cant wait to see this implemented :D

I just discovered it and DAMN!!! so neat!!

**Comment by BeatLink** [comment]
Nice! I can close this issue!
