### ISSUE TITLE
Cortana icon still on taskbar win10 2004

### ISSUE THREAD

**Issue by kokotas89** [builtbybel/privatezilla#28]
# Take Cortana off the taskbar
reg add HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced /v ShowCortanaButton /t REG_DWORD /d 0 /f

The above command removed the cortana icon from the taskbar. Maybe it should be added to privatezilla.

**Comment by Belim** [comment]
I'll check this and add it to option "Uninstall Cortana"  if it works.
Thanks 💯

**Comment by Belim** [comment]
Added https://github.com/builtbybel/privatezilla/releases/tag/0.42.0
