### ISSUE TITLE
Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by BenTen** [builtbybel/privatezilla#33]
Tried to run on W10 but Windows Defender just kick it because Trojan:Win32/Zpevdo.B

**Comment by kriskillerz** [comment]
Same issue for me with Vivaldi that stop dl from github.

**Comment by sky4055** [comment]
> 
> 
> Same issue for me with Vivaldi that stop dl from github.

same here, with Firefox (Windows 10)

**Comment by Belim** [comment]
It's a false positive guys. I've reported it to MS and it will be fixed in some hours
