### ISSUE TITLE
Can't find the script files?

### ISSUE THREAD

**Issue by dubepaul** [builtbybel/privatezilla#36]
Hello! I just extracted PZ in C:\opt\PrivateZilla\ and the script zip into C:\opt\PrivateZilla\scripts
Then I run PZ, go scripts, I tick any script ex. Blocking Telemetry IPs via Windows Firewall, I try to apply the script and I get the following error... (The system cannot find the file specified)

My guess would be some weird Powershell configuration issue on my computer but I wonder what's really hapenning here!

Thank you
Paul

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Privatezilla.MainWindow.<>c__DisplayClass28_1.<BtnDoPS_Click>b__1()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Privatezilla.MainWindow.<BtnDoPS_Click>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by DrSaad77** [comment]
just checked, everything is fine.
did yu check the presencer of the "scripts" in the folder??

**Comment by Belim** [comment]
Please make a complete screenshot of the application and error message when it is generated

This does not look like a faulty Powershell config. It just can't execute the scripts from Privatezilla because they don't exist. Thats's strange

**Comment by dubepaul** [comment]
Yes, the scripts folder is in the same folder as privatezilla exe.
As mentioned, I suspect something’s wrong on *my* system. Would you be interested to understand / prevent my issue, maybe you can provide me a debugging-enabled exe of actual version ?

Thanks
Paul


De : DrSaad77 <notifications@github.com>
Envoyé : Sunday, November 01, 2020 19:32
À : builtbybel/privatezilla <privatezilla@noreply.github.com>
Cc : Paul Dubé <dubepaul@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [builtbybel/privatezilla] Can't find the script files? (#36)


just checked, everything is fine.
did yu check the presencer of the "scripts" in the folder??

**Comment by DrSaad77** [comment]
hum, it looks like u said it is more related to your system than to Privatezilla. Those scripts are fine, except for Revert change that do not success much... At least in my case.
Maybe yu used another Debloater in the past, that why now this is happening... 
Generally, this Debload stuff is best succefully on a fresh installed system...
Perso, I am going to reinstall Win 10, and debload... For Win Apps, I used Win10Debloater of Sycnex, I like to be more able to choose what Win Apps are removed...
At leat that is my advice to you, cause looking to resolve such complexe error is not evident...

**Comment by dubepaul** [comment]
Allright, and don't worry I completely agree and don't need my error resolved, just wanted to make sure you didn't have some problem to fix on your side :)

Thank you and have a great day
