### ISSUE TITLE
NoAutoUpdate does the opposite.

### ISSUE THREAD

**Issue by Cereal-Killa** [builtbybel/privatezilla#49]
"NoAutoUpdate" value should be set to 1 in order to prevent the automatic updates, atm it's been set to 0 which is the opposite effect as it enabled auto updates.

https://github.com/builtbybel/privatezilla/blob/master/src/Privatezilla/Settings/Updates/DisableUpdates.cs:
`Registry.SetValue(NoAutoUpdate, "NoAutoUpdate", 0, RegistryValueKind.DWord);`

https://docs.microsoft.com/de-de/security-updates/windowsupdateservices/18127499

![image](https://user-images.githubusercontent.com/25939765/117512513-26f44600-af66-11eb-88b7-c7f50a051e8d.png)

PR: https://github.com/builtbybel/privatezilla/pull/50/files

**Comment by Belim** [comment]
Thanks 👍 
Here it is fixed https://github.com/builtbybel/privatezilla/releases/tag/0.50.0
