### ISSUE TITLE
Privatezilla for Windows 11

### ISSUE THREAD

**Issue by xenstar** [builtbybel/privatezilla#60]
Hello, Microsoft just released stable version of Windows 11 today. I have upgraded, and there was no error. Please make privatezilla compatible with Windows 11 too. As many people will be upgrading in coming days.

**Comment by Belim** [comment]
just switch to my [ThisIsWin11](https://github.com/builtbybel/ThisIsWin11) tools. both Privatezilla and Bloatbox are integrated in this app.

i don't think I will roll out Privatezilla for Windows 11, no time unfortunately.

**Comment by xenstar** [comment]
Awesome. I will check it out.

**Comment by xenstar** [comment]
Since Windows 11 released the stable version today. Can you please check it with the stable version if everything working smoothly or not?
