### ISSUE TITLE
Removal of built-in apps is not working on Local Account

### ISSUE THREAD

**Issue by akashblsbrmnm** [builtbybel/privatezilla#64]
With Privatezilla, cannot remove the built-in Microsoft apps. It shows Applied Status but doesn't removes.
When Tried on Administrator account, it does the job ! Please fix this.

OS : Windows 10
Version : 10.0.19043 Build 19043

**Comment by notbluu** [comment]
I believe to remove the built-in apps you'd need an administrator version of the app running to work.

**Comment by akashblsbrmnm** [comment]
Ohh yeah ! Thanks for replying.
